version: '3'

networks:
  dokploy-network:
    external: true

services:
  youtubemusicbetabot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3002:3002"
    networks:
      - dokploy-network
    restart: unless-stopped